### ISSUE TITLE
model

### ISSUE THREAD

**Issue by flynnamy** [wuqiuche/micromotion-styleGAN#1]
Hi, could you please share model weights with baidu cloud disk? Thanks! @wuqiuche

**Comment by wuqiuche** [comment]
Thank you very much for your interest in this project. However, these pre-trained models are released by other repositories, and we just use their released models. Therefore, we cannot distribute their pre-trained models. Sorry for the inconvenience!

As introduced in the README, you can find the original pre-trained model we used from the following repositories:
(a) [StyleCLIP](https://github.com/orpatashnik/StyleCLIP)
(b) [restyle-encoder](https://github.com/yuval-alaluf/restyle-encoder)
Specifically, the models we used are:
(a) [Inverter](https://drive.google.com/file/d/1sw6I2lRIB0MpuJkpc8F5BJiSZrc0hjfE/view)
(b) [Generator](https://drive.google.com/file/d/1EM87UquaoQmk17Q8d5kYIAHqu0dkYqdT/view)
(c) [Identity loss model](https://drive.google.com/file/d/1KW7bjndL3QG3sxBbZxreGHigcCCpsDgn/view)
